[build]
  # No build command needed for static site
  publish = "."

[build.environment]
  # Environment variables for the build

# Form handling settings
[[plugins]]
  package = "@netlify/plugin-forms"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules
[[redirects]]
  from = "/jasontuttle"
  to = "/"
  status = 301

[[redirects]]
  from = "/tuttle"
  to = "/"
  status = 301

# Form settings
[forms]
  # Enable form detection
  enabled = true

# Email notifications for form submissions
[[forms.notifications]]
  type = "email"
  event = "submission"
  to = "info@jasontuttle.com"  # Update this with your actual email
  subject = "New Campaign Website Contact"